import os
import shutil
import subprocess
import numpy as np
import time
import re
from io import StringIO
import math

def main():
    
    data_dir = "lambda-adaptive"
    flow_vtk_dir = os.path.join(data_dir, "flow_vtk")
    deltat = 0.1
    numtimesteps = 200
    num_time_samples = 10  
    lambda_values = np.linspace(1, 20, 5)
    betav_values = np.linspace(0.2, 0.9, 1)
    alphapar_values = np.linspace(0.2, 0.9, 1)
    steady_state = True 

    print(f"Generated {len(lambda_values)} training lambda values: {lambda_values}")
    print(f"Generated {len(betav_values)} training betav values: {betav_values}")
    prepare_data_directory(data_dir, flow_vtk_dir)
    clear_vtk_files()

    total_time = deltat * numtimesteps
    if steady_state:
        time_indices = [numtimesteps] 
    else:
        time_indices = generate_log_time_steps(total_time, num_time_samples, deltat)

    save_parameter_times("parameters.txt", lambda_values, betav_values, alphapar_values,
                         deltat, numtimesteps, time_indices)

    run_simulations(
        executable="./extrudate_swell2d_c",
        lambda_vals=lambda_values,
        betav_vals=betav_values,
        alphapar_vals=alphapar_values,
        deltat=deltat,
        numtimesteps=numtimesteps,
        time_indices=time_indices,
        vtk_dir=flow_vtk_dir,
        data_dir=data_dir
    )

    if os.path.exists("parameters.txt"):
        shutil.move("parameters.txt", os.path.join(data_dir, "parameters.txt"))
        print(f"📄 Moved parameters.txt → {data_dir}")

    # Move mesh.vtk into data_dir (generated by the first Fortran call)
    if os.path.exists("mesh.vtk"):
        shutil.move("mesh.vtk", os.path.join(data_dir, "mesh.vtk"))
        print(f"🧩 Moved mesh.vtk → {data_dir}")

    print("\n🎉 All full simulations done!")


def prepare_data_directory(data_dir, flow_vtk_dir):
    os.makedirs(data_dir, exist_ok=True)
    if os.path.exists(flow_vtk_dir):
        shutil.rmtree(flow_vtk_dir)
        print(f"🚹 Removed old VTK directory: {flow_vtk_dir}")
    os.makedirs(flow_vtk_dir)
    print(f"📁 Created new VTK folder: {flow_vtk_dir}")

    files_to_delete = [
        "parameters.txt", "snapshots.txt", "pressure.txt",
        "mesh_coor2.txt", "c-trace.txt", "b-trace.txt",
        "mesh.msh", "mesh.geo"]
    for file in files_to_delete:
        for location in [".", data_dir]:
            path = os.path.join(location, file)
            if os.path.exists(path):
                os.remove(path)
                print(f"🖑️ Deleted: {path}")


FORTRAN_TEMP_FILES = ["cval.out", "outputmesh.out", "outputmesh_inlet.out"]


def clear_fortran_temp_files():
    for f in FORTRAN_TEMP_FILES:
        if os.path.exists(f):
            os.remove(f)


def clear_vtk_files():
    for file in os.listdir("."):
        if file.endswith(".vtk"):
            try:
                os.remove(file)
                print(f"🪼 Deleted VTK file: {file}")
            except Exception as e:
                print(f"⚠️ Could not delete {file}: {e}")


# M3 mesh resolution (from convergence study)
DX_BOX   = 0.2
DX_WALL  = 0.04
DX_INLET = 0.1


def generate_input_string(lambda1, alphapar, betav, deltat, numtimesteps):
    s = StringIO()
    s.write("&comppar\n")
    s.write(f"lambda = {lambda1:.16f}\n")
    s.write(f"mobility = {alphapar:.16f}\n")
    s.write(f"betav = {betav:.16f}\n")
    s.write(f"deltat = {deltat:.16f}\n")
    s.write(f"numtimesteps = {numtimesteps}\n")
    s.write(f"dx_box   = {DX_BOX:.16f}\n")
    s.write(f"dx_wall  = {DX_WALL:.16f}\n")
    s.write(f"dx_inlet = {DX_INLET:.16f}\n")
    s.write("/\n")
    return s.getvalue()


def execute_simulation(executable, input_str):
    result = subprocess.run([executable], input=input_str.encode(),
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.stderr:
        print(f"[ERROR] stderr: {result.stderr.decode()}")
    return result.stdout.decode()

def generate_log_time_steps(total_time, num_points, deltat):
    """
    Generate logarithmically spaced time indices to capture transient behavior early.
    """
    # avoid log(0) by starting slightly after t=0
    t_min = deltat
    t_max = total_time

    # logarithmic spacing in time
    times = np.geomspace(t_min, t_max, num_points)

    # convert to time step indices
    indices = [round(t / deltat) for t in times]

    # ensure indices are within valid range
    indices = [max(1, min(i, math.ceil(total_time / deltat))) for i in indices]

    return np.unique(indices)


def generate_uniform_time_steps(total_time, num_points, deltat):
    times = np.linspace(0, total_time, num_points)
    indices = [round(t / deltat) for t in times]
    indices = [max(1, min(i, math.ceil(total_time / deltat))) for i in indices]
    return np.unique(indices)


def filter_and_append_output_files(data_dir, time_indices, numtimesteps, lam, betav, alphapar):
    output_files = ["snapshots.txt", "pressure.txt", "mesh_coor2.txt",
                    "c-trace.txt", "b-trace.txt"]
    for file in output_files:
        if not os.path.exists(file):
            continue
        with open(file, 'r') as f:
            lines = f.readlines()
        total_lines = len(lines)
        if total_lines == 0 or total_lines % numtimesteps != 0:
            print(f"⚠️ {file}: {total_lines} lines not divisible by {numtimesteps} steps, skipping")
            os.remove(file)
            continue
        lines_per_step = total_lines // numtimesteps
        filtered_lines = []
        for idx in time_indices:
            start = (idx - 1) * lines_per_step
            end = idx * lines_per_step
            filtered_lines.extend(lines[start:end])
        dst = os.path.join(data_dir, file)
        with open(dst, 'a') as f:
            f.writelines(filtered_lines)
        os.remove(file)
        print(f"📜 Appended filtered {file} ({lines_per_step} lines/step) for λ={lam:.3f}, β={betav:.3f}, α={alphapar:.3f}")
        
def move_vtk_files(lam, betav, alphapar, vtk_dir):
    # create subfolder per parameter set
    subfolder = os.path.join(vtk_dir, f"lambda-{lam:.3f}_beta-{betav:.3f}_alpha-{alphapar:.3f}")
    os.makedirs(subfolder, exist_ok=True)

    for file in os.listdir("."):
        if file.endswith(".vtk"):
            src = os.path.join(".", file)
            dst = os.path.join(subfolder, file)
            shutil.move(src, dst)
            print(f"📦 Moved {file} → {subfolder}")


def save_parameter_times(filepath, lambda_values, betav_values, alphapar_values,
                         deltat, numtimesteps, time_indices):
    with open(filepath, 'w') as f:
        for alphapar in alphapar_values:
            for betav in betav_values:
                for lam in lambda_values:
                    for i in time_indices:
                        t = deltat * i
                        f.write(f"{lam:.16f} {betav:.16f} {alphapar:.16f} {t:.16f} {i}\n")


def run_simulations(executable, lambda_vals, betav_vals, alphapar_vals,
                    deltat, numtimesteps, time_indices, vtk_dir, data_dir):
    start_time = time.time()

    output_files = ["snapshots.txt", "pressure.txt", "mesh_coor2.txt",
                    "c-trace.txt", "b-trace.txt"]
    for file in output_files:
        open(os.path.join(data_dir, file), 'w').close()

    for alphapar in alphapar_vals:
        for betav in betav_vals:
            for lam in lambda_vals:
                print(f"\n🚀 Running λ = {lam:.3f}, β = {betav:.3f}, α = {alphapar:.3f}")
                input_str = generate_input_string(lam, alphapar, betav, deltat, numtimesteps)
                clear_fortran_temp_files()
                _ = execute_simulation(executable, input_str)
                move_vtk_files(lam, betav, alphapar, vtk_dir)

                filter_and_append_output_files(data_dir, time_indices, numtimesteps, lam, betav, alphapar)

    print(f"\n🌟 All simulations done in {time.time() - start_time:.2f} seconds.")


if __name__ == "__main__":
    main()
